language: node_js
node_js:
  - 0.12

env: BROWSERS=chrome E2E_BROWSERS=chrome

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - scripts/private/test-all.sh
